# Site settings
title: Shane Logsdon
subtitle: Polyglot Developer
email: shane@logsdon.io
description: |
  I develop things. Sometimes, I write about them here.
  Let's start a conversation.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://shane.logsdon.io' # the base hostname & protocol for your site
twitter:
  username: shanelogsdon
github:
  username: slogsdon

# Build settings
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - CNAME
  - LICENSE
  - README.md
permalink: /posts/:title/
markdown: kramdown
kramdown:
  input: GFM
sass:
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
